# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: SETTING ENVIRONMENT VARIABLE
        run:  |
          echo "$SERVICE_ACCOUNT_PATH" | base64 --decode > firebase-adminsdk.json
          echo "SERVICE_ACCOUNT_PATH=$PWD/firebase-adminsdk.json" >> $GITHUB_ENV
          echo "GMAIL=$GMAIL" >> $GITHUB_ENV
          echo "GMAIL_PASS=$GMAIL_PASS" >> $GITHUB_ENV
        shell: bash
        env:
          SERVICE_ACCOUNT_PATH: ${{ secrets.SERVICE_ACCOUNT_PATH }}
          GMAIL: ${{ secrets.GMAIL }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      - run: npm ci
      - run: npm install
      - run: npm run test